language: python

python:
  - 3.6

env:
  matrix:
    - TEST_PACAKGE=modules/bissell
    - TEST_PACAKGE=modules/consul
    - TEST_PACAKGE=modules/couchdb
    - TEST_PACAKGE=modules/gitlab
    - TEST_PACAKGE=modules/gogs
    - TEST_PACAKGE=modules/irods
    - TEST_PACAKGE=modules/mongo
    - TEST_PACAKGE=modules/samtools
#    - TEST_LATEST_ONLY=0
#    - TEST_LATEST_ONLY=1

services:
  - docker

before_install:
  - pip install codecov
  - pip install --disable-pip-version-check -r test_requirements.txt

install:
  - pip install --disable-pip-version-check -r requirements.txt

jobs:
  include:
    - stage: test_common
      script:
        - PYTHONPATH=. coverage run -m unittest discover -v -s useintest/tests/executables
        - PYTHONPATH=. coverage run -m unittest discover -v -s useintest/tests/services
        - coverage run setup.py -q install
        - coverage combine -a
        - coverage report
      env: []

    - stage: test_modules
      install:
        - pip install --disable-pip-version-check -r "${TESTED_PACKAGE_DIRECTORY}/requirements.txt" || true
      script:
        - PYTHONPATH=. coverage run -m unittest discover -v -s "useintest/tests/${TEST_PACAKGE}"
        - coverage run setup.py -q install
        - coverage combine -a
        - coverage report

#    - stage: test_all:





#  after_success:
#    - codecov
