language: python

python:
  - 3.5

services:
  - docker

env:
  matrix:
    - SINGLE_TEST_SETUP=v0_16_1_WITH_IRODS_3_3_1
    - SINGLE_TEST_SETUP=v0_16_2_WITH_IRODS_3_3_1
    - SINGLE_TEST_SETUP=v0_16_2_WITH_IRODS_4_1_8
    - SINGLE_TEST_SETUP=v0_16_3_WITH_IRODS_3_3_1
    - SINGLE_TEST_SETUP=v0_16_3_WITH_IRODS_4_1_8
    - SINGLE_TEST_SETUP=v0_16_4_WITH_IRODS_3_3_1
    - SINGLE_TEST_SETUP=v0_16_4_WITH_IRODS_4_1_8
    - SINGLE_TEST_SETUP=v0_16_4_WITH_IRODS_4_1_9

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=testwithbaton --cover-inclusive --exclude-test=testwithbaton.tests._common.create_tests_for_all_baton_setups

after_success:
  - codecov
