language: python

python:
  - 3.6

env:
  matrix:
    - TEST_LATEST_ONLY=0
    - TEST_LATEST_ONLY=1

services:
  - docker

before_install:
  - pip install nose
  - pip install nose-exclude
  - pip install codecov

install:
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=useintest --cover-inclusive --exclude-test=useintest.tests.services._common.TestDockerisedServiceControllerSubclass --exclude-test=useintest.tests.services._common.create_tests

after_success:
  - codecov
