language: python

python:
  - 3.6

env:
  matrix:
    - TEST_PACAKGE=executables
    - TEST_PACAKGE=services
    - TEST_PACAKGE=modules/bissell
    - TEST_PACAKGE=modules/consul
    - TEST_PACAKGE=modules/couchdb
    - TEST_PACAKGE=modules/gitlab
    - TEST_PACAKGE=modules/gogs
    - TEST_PACAKGE=modules/irods
    - TEST_PACAKGE=modules/mongo
    - TEST_PACAKGE=modules/samtools
#    - TEST_LATEST_ONLY=0
#    - TEST_LATEST_ONLY=1

services:
  - docker

before_install:
  - export TESTED_PACKAGE_DIRECTORY="useintest/modules/${TEST_PACAKGE}"
  - pip install codecov
  - pip install --disable-pip-version-check -r test_requirements.txt

install:
  - pip install -r requirements.txt
  - pip install --disable-pip-version-check -r ${TESTED_PACKAGE_DIRECTORY}/requirements.txt || true

script:
  - PYTHONPATH=. coverage run -m unittest discover -v -s "${TEST_PACAKGE}"
  - coverage run setup.py -q install
  - coverage combine -a
  - coverage report

after_success:
  - codecov
